version: "3.8"

services:
  message-pusher:
    image: registry.cn-guangzhou.aliyuncs.com/landwind/message-pusher:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro